stagmenfashion/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = (
    [path("admin/", admin.site.urls), path("", include("web.urls", namespace="web"))]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

web/urls.py
from django.urls import path

from . import views


app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("category/<str:slug>/", views.CategoryProductListView.as_view(), name="category_list"),
    path("subcategory/<str:slug>/", views.SubcategoryProductListView.as_view(), name="subcategory_list"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("privacy-policy/", views.PrivacyPolicyView.as_view(), name="privacy_policy"),
    path("terms-and-conditions/", views.TermsAndConditionsView.as_view(), name="terms_and_conditions"),
    path("cookies-policy/", views.CookiesPolicyView.as_view(), name="cookies_policy"),
    path("refund-policy/", views.RefundPolicyView.as_view(), name="refund_policy"),
    path("product/<str:slug>/", views.ProductView.as_view(), name="product_view"),
    path("branch/<str:slug>/", views.BranchView.as_view(), name="branch_view"),
    path("checkout/<str:pk>/", views.CheckoutView.as_view(), name="checkout"),
    path("payment/<str:pk>/", views.PaymentView.as_view(), name="payment"),
    path("callback/verify/<str:pk>/", views.PaymentCallback.as_view(), name="payment_callback"),
    path("complete-order/<str:pk>/", views.CompleteOrderView.as_view(), name="complete_order"),
    path("track/", views.TrackOrdersView.as_view(), name="track_orders"),
    path("cart/", views.CartView.as_view(), name="cart"),
    path("order/delete/<str:pk>/", views.RemoveCartItemView.as_view(), name="order_delete"),
    path("orders/", views.OrderListView.as_view(), name="order_list"),
    path("orders/refresh/", views.refresh_orders, name="order_refresh"),
    path("order/<str:pk>/", views.OrderDetailView.as_view(), name="order_view"),
]

templates/web/about.html
{% extends 'web/base.html' %}
{% load static custom_filters humanize %}

{% block content %}
<!-- ======== Top Breadcrubms ========= -->
<div class="gray py-3">
	<div class="container-fluid">
		<div class="row">
			<div class="colxl-12 col-lg-12 col-md-12">
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">About Us</li>
					</ol>
				</nav>
			</div>
		</div>
	</div>
</div>
<!-- ======== Top Breadcrubms ========= -->

<!-- ======== About Us Detail ========= -->
<section class="middle">
	<div class="container">
		<div class="row justify-content-between">

			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
				<div class="abt_caption">
					<h2 class="ft-medium mb-4">The Stagmenfashion Story</h2>
					<p class="mb-4 fs-15">
						Stagmenfashion, the brainchild of our visionary founder, emerged onto the global fashion stage in 2017, and it has since
						been a testament to unwavering principles and a celebration of Kerala's rich heritage. Our brand is deeply rooted in a
						profound love for the great outdoors, an enduring passion that propels us to constantly redefine the intersection of
						exploration and style.
					</p>
					<p class="mb-4 fs-15">
						Our journey at Stagmenfashion unfolds as a mesmerizing tapestry, one that seamlessly weaves together timeless traditions
						with a contemporary flair. We draw our inspiration from the cultural opulence of Kerala, a land brimming with vibrant
						landscapes, diverse communities, and exquisite artistry. These influences harmoniously meld with our unwavering
						commitment to innovative fashion, resulting in collections that resonate with a global audience while paying homage to
						our deep-seated origins.
					</p>
					<p class="mb-4 fs-15">
						At the core of Stagmenfashion's philosophy lies the belief that fashion should be a medium for storytelling. Our
						garments transcend being mere fabric and stitches; they serve as a canvas for personal expression and a reflection of
						individuality. Crafting pieces that empower individuals to embrace their unique identities and stride confidently into
						the world is a source of immense pride for us. With each design, we extend an invitation to embark on a journey of
						self-discovery and exploration, encouraging everyone to push the boundaries of what fashion can achieve.
					</p>
				
				</div>
			</div>

			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
				<div class="abt_caption" style="min-height: 600px;">
					<img src="{% static 'web/img/about.jpg' %}" class="img-fluid rounded w-100" alt="" style="height: 600px;overflow:hidden;object-fit:cover;object-position: center;" />
				</div>
			</div>

		</div>
	</div>
</section>

{% endblock %}

templates/web/branch_detail.html
{% extends 'web/base.html' %}
{% load static custom_filters humanize %}

{% block content %}
<!-- ======== Top Breadcrubms ========= -->
<div class="gray py-3">
	<div class="container-fluid">
		<div class="row">
			<div class="colxl-12 col-lg-12 col-md-12">
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">About Us</li>
					</ol>
				</nav>
			</div>
		</div>
	</div>
</div>
<!-- ======== Top Breadcrubms ========= -->

<!-- ======== About Us Detail ========= -->
<section class="middle">
	<div class="container">
		<div class="row justify-content-between">

			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
				<div class="abt_caption">
					<h2 class="ft-medium mb-4">The Stagmenfashion - {{object.name}}</h2>
					<div class="card-wrap-body mb-4">
						<p>{{branch.address|linebreaksbr}}</p>
						<p class="lh-1"><span class="text-dark ft-medium">Email:</span> {{branch.email}}</p>
						<p class="lh-1"><span class="text-dark ft-medium">Phone:</span> {{branch.phone}}</p>
					</div>
				</div>
			</div>

			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
				<div class="abt_caption" style="height: 600px;">
					{% if object.image %}
					<img src="{{object.image.url}}" class="img-fluid rounded w-100" alt="" style="height: 600px;overflow:hidden;object-fit:cover;object-position: center;" />
					{% else %}
					<img src="{% static 'web/img/about.jpg' %}" class="img-fluid rounded w-100" alt="" style="height: 600px;overflow:hidden;object-fit:cover;object-position: center;" />
					{% endif %}
				</div>
			</div>

		</div>
	</div>
</section>

{% endblock %}

templates/web/callback.html
{% extends 'web/base.html' %}
{% load static custom_filters humanize %}

{% block content %}
<!-- ======== Top Breadcrubms ========= -->
<div class="gray py-3">
	<div class="container-fluid">
		<div class="row">
			<div class="colxl-12 col-lg-12 col-md-12">
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">Payment Callback</li>
					</ol>
				</nav>
			</div>
		</div>
	</div>
</div>
<!-- ======== Top Breadcrubms ========= -->

<!-- ======== About Us Detail ========= -->
<section class="middle">
	<div class="container">

		<div class="row justify-content-center">
			{% if object.is_ordered %}
			<div class="col-12 col-md-10 col-lg-8 col-xl-6 text-center">
				<div class="p-4 d-inline-flex align-items-center justify-content-center circle bg-light-success text-success mx-auto mb-4">
					<i class="lni lni-heart-filled fs-lg"></i>
				</div>
				<h2 class="mb-2 ft-bold">Your Order is Completed!</h2>
				<p class="ft-regular fs-md mb-5">
					Your order 
					<span class="text-body text-dark">{{object.order_id}} </span>
					has been completed.
				</p>
				<a class="btn btn-dark" href="{% url 'web:track_orders' %}">Track Your Orders</a>
			</div>

			{% else %}

			<div class="col-12 col-md-10 col-lg-8 col-xl-6 text-center">
				<h2 class="mb-2 ft-bold">Your Order is Not Completed!</h2>
				<p class="ft-regular fs-md mb-5">
					Your order 
					<span class="text-body text-dark">{{object.order_id}} </span>
					has not been completed.
				</p>
				<a class="btn btn-dark" href="{% url 'web:checkout' object.pk %}">Go back to Checkout</a>
			</div>

			{% endif %}
		</div>

	</div>
</section>

{% endblock %}

templates/web/cart.html
{% extends 'web/base.html' %}
{% load static custom_filters crispy_forms_tags humanize %}

{% block content %}
<!-- ======== Top Breadcrubms ========= -->
<div class="gray py-3">
	<div class="container-fluid">
		<div class="row">
			<div class="colxl-12 col-lg-12 col-md-12">
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">Shopping Cart</li>
					</ol>
				</nav>
			</div>
		</div>
	</div>
</div>


<section class="middle">
	<div class="container">

		<div class="row">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
				<div class="text-center d-block mb-5">
					<h2>Shopping Cart</h2>
				</div>
			</div>
		</div>

		{% if cart_items %}

		<div class="row justify-content-between">
			<div class="col-12 col-lg-7 col-md-12">
				<ul class="list-group list-group-sm list-group-flush-y list-group-flush-x mb-4">

					{% for item in cart_items %}
					<li class="list-group-item">
						<div class="row align-items-center">
							<div class="col-3">
								<a href="{{item.product_option.product.get_absolute_url}}">
									<img src="{{item.product_option.product.image.small.url}}" alt="..."
										class="img-fluid">
								</a>
							</div>
							<div class="col d-flex align-items-center">
								<div class="cart_single_caption pl-2">
									<h4 class="product_title fs-md ft-medium mb-2 lh-1">
										{{item.product_option.product.name}}</h4>
									<div class="d-flex flex-wrap mb-2">
										<p class="mb-1 lh-1 mr-4"><span class="text-dark">Size: {{item.product_option}}</span></p>
										<p class="mb-1 lh-1 mr-4"><span class="text-dark">Price: {{item.price|intcomma|get_currency:request.user}}</span></p>
										<p class="mb-1 lh-1 mr-4"><span class="text-dark">QTY: {{item.quantity}}</span></p>
									</div>
									<h4 class="fs-md ft-medium mb-3 lh-1">{{item.price|intcomma|get_currency:request.user}}
									</h4>
								</div>
							</div>
						</div>
					</li>
					{% endfor %}

				</ul>

			</div>

			<div class="col-12 col-md-12 col-lg-4">
				<div class="card mb-4 gray">
					<div class="card-body p-4">
						<ul class="list-group list-group-sm list-group-flush-y list-group-flush-x">
							<li class="list-group-item d-flex text-dark fs-sm ft-regular">
								<span>Subtotal</span> <span class="ml-auto text-dark ft-medium">{{order.subtotal|intcomma|get_currency:request.user}}</span>
							</li>
							<li class="list-group-item d-flex text-dark fs-sm ft-regular">
								<span>Shipping</span> <span class="ml-auto text-dark ft-medium">Calculated at Checkout</span>
							</li>
							<li class="list-group-item d-flex text-dark fs-sm ft-regular">
								<span>Total</span> <span class="ml-auto text-dark ft-medium">{{order.payable|intcomma|get_currency:request.user}} + Shipping</span>
							</li>
						</ul>
					</div>
				</div>
				
				<form action="" method="post">
					{% csrf_token %}
					{{form|crispy}}
					<input type="hidden" name="order_id" value="{{order.pk}}">
					<button type="submit" class="btn btn-block btn-dark mb-3" href="{% url 'web:checkout' order.pk %}">Proceed to Checkout</button>
				</form>
					
					<a class="btn-link text-dark ft-medium" href="{% url 'web:product_list' %}">
					<i class="ti-back-left mr-2"></i> Continue Shopping
				</a>
			</div>

		</div>

		{% else %}

		<div class="row">
			<div class="col-10 mx-auto text-center">
				<p>There is nothing in your cart to Checkout</p>
			</div>
		</div>

		{% endif %}
		
	</div>
</section>
<!-- ======== Product Detail End ========= -->

{% endblock %}

templates/web/checkout.html
{% extends 'web/base.html' %}
{% load static custom_filters thumbnail crispy_forms_tags humanize %}


{% block content %}

<div class="gray py-3">
	<div class="container-fluid">
		<div class="row">
			<div class="colxl-12 col-lg-12 col-md-12">
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">Checkout</li>
					</ol>
				</nav>
			</div>
		</div>
	</div>
</div>


<section class="middle">
	<div class="container">

		<div class="row">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
				<div class="text-center d-block mb-5">
					<h2>Checkout</h2>
				</div>
			</div>
		</div>

		{% if cart_items %}

		<form action="" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="row justify-content-between">

				<div class="col-12 col-lg-7 col-md-12">
					<h5 class="mb-4 ft-medium">Billing Details</h5>
					<div class="row mb-2">
						
						{% for err in form.non_field_errors %}
						<div class="col-12">
							<div class="alert alert-danger">
								{{err}}
							</div>
						</div>
						{% endfor %}

						{% if form.errorrs %}
						<div class="col-12">
							<div class="alert alert-danger">
								{{form.errors}}
							</div>
						</div>
						{% endif %}

						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
							{{form.first_name|as_crispy_field}}
						</div>

						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
							{{form.last_name|as_crispy_field}}
						</div>

						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							{{form.address_line_1|as_crispy_field}}
						</div>

						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							{{form.address_line_2|as_crispy_field}}
						</div>

						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							{{form.city|as_crispy_field}}
						</div>

						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							{{form.district|as_crispy_field}}
						</div>

						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							{{form.province|as_crispy_field}}
						</div>

						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							{{form.pincode|as_crispy_field}}
						</div>

						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							{{form.mobile|as_crispy_field}}
						</div>

						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							{{form.alternate_mobile|as_crispy_field}}
						</div>

						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							{{form.notes|as_crispy_field}}
						</div>

					</div>
				</div>

				<!-- Sidebar -->
				<div class="col-12 col-lg-4 col-md-12">
					<div class="d-block mb-3">
						<h5 class="mb-4">Order Items ({{cart_items|length}})</h5>
						<ul class="list-group list-group-sm list-group-flush-y list-group-flush-x mb-4">
					
							{% for item in cart_items %}
							<li class="list-group-item">
								<div class="row align-items-center">
									<div class="col-3">
										<a href="{{item.product_option.product.get_absolute_url}}">
											<img src="{{item.product_option.product.image.medium.url}}" alt="..." class="img-fluid">
										</a>
									</div>
									<div class="col d-flex align-items-center">
										<div class="cart_single_caption pl-2">
											<h4 class="product_title fs-md ft-medium mb-2 lh-1">{{item.product_option.product.name}}</h4>
											<p class="mb-1 lh-1"><span class="text-dark">Size: {{item.product_option}}</span></p>
											<div class="d-flex flex-wrap mb-2">
												<p class="mb-1 lh-1 mr-3"><span class="text-dark">QTY: {{item.quantity}}</span></p>
												<p class="mb-1 lh-1"><span class="text-dark">Price: {{item.price|intcomma|get_currency:request.user}}</span></p>
											</div>
											<h4 class="fs-md ft-medium mb-3 lh-1">{{item.price|intcomma|get_currency:request.user}}</h4>
										</div>
									</div>
								</div>
							</li>
							{% endfor %}
					
						</ul>
					</div>

					<div class="card mb-4 gray">
						<div class="card-body p-4">
							<ul class="list-group list-group-sm list-group-flush-y list-group-flush-x">
								<li class="list-group-item d-flex text-dark fs-sm ft-regular">
									<span>Subtotal</span> <span class="ml-auto text-dark ft-medium">{{order.subtotal|intcomma|get_currency:request.user}}</span>
								</li>
								<li class="list-group-item d-flex text-dark fs-sm ft-regular">
									<span>Shipping</span> <span class="ml-auto text-dark ft-medium">{{order.shipping|intcomma|get_currency:request.user}}</span>
								</li>
								<li class="list-group-item d-flex text-dark fs-sm ft-regular">
									<span>Total</span> <span class="ml-auto text-dark ft-medium">{{order.payable|intcomma|get_currency:request.user}}</span>
								</li>
							</ul>
						</div>
					</div>

					<button class="btn btn-block btn-dark mb-3" type="submit">Proceed to Payment</button>
				</div>

			</div>
		</form>

		{% else %}
		<div class="row">
			<div class="col-10 mx-auto text-center">
				<p>There is nothing in your cart to Checkout</p>
			</div>
		</div>
		{% endif %}
		

	</div>
</section>

{% endblock %}

templates/web/orders.html
{% extends 'web/base.html' %}
{% load static custom_filters humanize %}
{% load render_table from django_tables2 %}

{% block content %}


<section class="bg-cover pt-5 table_page">
	<div class="container">
		<div class="row align-items-center justify-content-center">
			<div class="col-6">
				<div class="text-start">
					<h6 class="ft-medium mb-0">{{title|upper}}</h6>
				</div>
			</div>
			<div class="col-6">
				<div class="text-right">
					<a href="{% url 'web:order_refresh' %}" class="btn btn-sm border">Refresh Orders</a>
				</div>
			</div>

		</div>
	</div>

	
	<div class="container mt-4">
		<div class="table-responsive">
			{% render_table table %}
		</div>
	</div>

</section>

{% endblock %}

templates/web/payment.html
{% extends 'web/base.html' %}
{% load static custom_filters thumbnail humanize %}


{% block content %}

<div class="gray py-3">
	<div class="container-fluid">
		<div class="row">
			<div class="colxl-12 col-lg-12 col-md-12">
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">Checkout</li>
					</ol>
				</nav>
			</div>
		</div>
	</div>
</div>


<section class="middle">
	<div class="container">

		<div class="row">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
				<div class="text-center d-block mb-5">
					<h2>Payment</h2>
				</div>
			</div>
		</div>

		{% if cart_items %}

		<div class="row justify-content-between">

			<!-- Sidebar -->
			<div class="col-12 col-lg-4 col-md-12 mx-auto">


				<div class="card mb-4 gray">
					<div class="card-body p-4">
						<ul class="list-group list-group-sm list-group-flush-y list-group-flush-x">
							<li class="list-group-item d-flex text-dark fs-sm ft-regular">
								<span>Subtotal</span> <span
									class="ml-auto text-dark ft-medium">{{order.subtotal|intcomma|get_currency:request.user}}</span>
							</li>
							<li class="list-group-item d-flex text-dark fs-sm ft-regular">
								<span>Shipping</span> <span
									class="ml-auto text-dark ft-medium">{{order.shipping|intcomma|get_currency:request.user}}</span>
							</li>
							<li class="list-group-item d-flex text-dark fs-sm ft-regular">
								<span>Total</span> <span
									class="ml-auto text-dark ft-medium">{{order.payable|intcomma|get_currency:request.user}}</span>
							</li>
						</ul>
					</div>
				</div>

				<button class="btn btn-block btn-dark mb-3" type="submit">Make Payment</button>
			</div>

		</div>

		{% else %}
		<div class="row">
			<div class="col-10 mx-auto text-center">
				<p>There is nothing in your cart to Checkout</p>
			</div>
		</div>
		{% endif %}


	</div>
</section>

{% endblock %}

templates/web/product_detail.html
{% extends 'web/base.html' %}
{% load static custom_filters crispy_forms_tags thumbnail humanize %}


{% block content %}
<!-- ======== Top Breadcrubms ========= -->
<div class="gray py-3">
	<div class="container-fluid">
		<div class="row">
			<div class="colxl-12 col-lg-12 col-md-12">
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item"><a href="{% url 'web:product_list' %}">Products</a></li>
						<li class="breadcrumb-item active" aria-current="page">{{object}}</li>
					</ol>
				</nav>
			</div>
		</div>
	</div>
</div>
<!-- ======== Top Breadcrubms ========= -->

<!-- ======== Product Detail ========= -->
<section class="middle">
	<div class="container">

		<div class="row">

			<div class="col-xl-5 col-lg-5 col-md-12 col-sm-12">
				<div class="sp-wrap product-slider">
					<a href="{{object.image.url}}" data-lightbox="roadtrip">
						<img src="{{object.image.medium.url}}" alt="">
					</a>
					{% for item in object.get_images %}
					<a href="{{item.image.url}}" data-lightbox="roadtrip">
						<img src="{{item.image.medium.url}}" alt="">
					</a>
					{% endfor %}
				</div>

				<div class='slider-nav'>
					<div><img src="{{object.image.medium.url}}"></div>
					{% for item in object.get_images %}
					<div><img src="{{item.image.medium.url}}"></div>
					{% endfor %}
				</div>

			</div>

			<div class="col-xl-7 col-lg-7 col-md-12 col-sm-12">
				<div class="prd_details">

					<div class="prt_01 mb-2">
						<div class="badge ft-regular ab-left text-upper pl-0">{{object.badge|default:""}}</div>
					</div>

					<div class="prt_02 mb-3">
						<h5 class="ft-bold mb-3">{{object.name}}</h5>
						<div class="text-left">
							<div class="star-rating align-items-center d-flex justify-content-left mb-1 p-0">
								<i class="fas fa-star filled"></i>
								<i class="fas fa-star filled"></i>
								<i class="fas fa-star filled"></i>
								<i class="fas fa-star filled"></i>
								<i class="fas fa-star filled"></i>
							</div>
							<div class="elis_rty">
								{% if object.offer_price %}
								<span class="ft-bold fs-lg text text-dark mr-1"><del>{{object.sale_price|intcomma|get_currency:request.user}}</del></span>
								<span class="ft-bold fs-lg text text-danger">{{object.offer_price|intcomma|get_currency:request.user}}</span>
								{% else %}
								<span class="ft-bold fs-lg text text-danger">{{object.sale_price|intcomma|get_currency:request.user}}</span>
								{% endif %}
							</div>
						</div>
					</div>

					{% if object.description %}
					<div class="prt_03 mb-4">
						<p>
							{{object.description|linebreaks}}
						</p>
					</div>
					{% endif %}

					<div class="prt_04 mb-4">
						<p class="d-flex align-items-center mb-1">Category:<strong
								class="fs-sm text-dark ft-medium ml-1">{{object.subcategory}}</strong></p>
					</div>

					<!-- Button trigger modal -->
					<button type="button" class="btn chart_btn" data-toggle="modal" data-target="#sizeModal">
						<svg focusable="false" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="tag_image"
							style="height: 20px;margin-right:10px">
							<path d="M0 0h24v24H0V0z" fill="none"></path>
							<path
								d="M21.11 2.89A3.02 3.02 0 0 0 18.95 2h-5.8c-.81 0-1.58.31-2.16.89L7.25 6.63 2.9 10.98a3.06 3.06 0 0 0 0 4.32l5.79 5.8a3.05 3.05 0 0 0 4.32.01l8.09-8.1c.58-.58.9-1.34.9-2.16v-5.8c0-.81-.32-1.59-.89-2.16zM20 10.85c0 .28-.12.54-.32.74l-3.73 3.74-4.36 4.36c-.41.41-1.08.41-1.49 0l-2.89-2.9-2.9-2.9a1.06 1.06 0 0 1 0-1.49l8.1-8.1c.2-.2.46-.3.74-.3l5.8-.01A1.05 1.05 0 0 1 20 5.05v5.8zM16 6c1.1 0 2 .9 2 2s-.9 2-2 2-2-.9-2-2 .9-2 2-2z">
							</path>
						</svg>
						Size Guide
					</button>


					{% if product.item_status == "Available" %}
					<div class="prt_05 mb-5">
						<div class="mb-7">
							<form action="" method="post" class="cart_form reload">
								{% csrf_token %}

								<div id="div_id_product_option" class="form-group">
									<label class=" requiredField">
										{{ form.product_option.label }}
										<span class="asteriskField">*</span>
									</label>

									<div class="">
										{% for radio in form.product_option %}
										<div class="form-check">
											<input type="radio" class="form-check-input" name="product_option" {{radio.data.value|check_stock}} value="{{ radio.data.value }}" required id="{{radio.id_for_label}}">
											<label  class="form-check-label {{radio.data.value|check_stock}}" for="{{radio.id_for_label}}">{{radio.choice_label}}</label>
										</div>
										{% endfor %}
									</div>
								</div>

								<div class="notice mb-3">
									<span class="d-block"><strong>O</strong> - Denote Oversized Apparels</span>
									<span class="d-block"><strong>R</strong> - Denote Regular Size Apparels</span>
								</div>

								<div class="flexitem flex-nowrap">
									{{form.quantity|as_crispy_field}}
									<div id="div_id_submit" class="form-group">
										<button type="submit" class="btn custom-height bg-dark px-3 w-100">ADD TO BAG</button>
									</div>
								</div>
							</form>
						</div>
					</div>

					{% elif product.item_status == "LaunchingSoon" %}
					<div class="prt_05 mb-5">
						<button type="button" class="btn custom-height bg-dark px-3">LAUNCHING SOON</button>
					</div>
					{% endif %}


				</div>
			</div>
		</div>

		<div class="row" style="margin-top: 80px;">
			<div class="col-12">
				<div class="disclaimers border p-4">
					<div class="mb-2">
						<h6>Exchange on Return</h6>
						<p>
							We are pleased to accommodate exchanges for items within a 15-day window from the date of
							receipt. Regrettably, if more than 15 days have elapsed since your purchase, we are unable
							to process an exchange. Contact us at +91 7736444674 for any product related assistance.
						</p>
					</div>
					<div class="b-2">
						<h6>Free delivery on orders over ₹2999</h6>
						<p> Free delivery with our standard delivery service on all orders above ₹2999 in india</p>
					</div>
				</div>
			</div>
		</div>

	</div>
</section>


{% include 'web/partials/sizeguide.html' %}


{% endblock %}

{% block javascript %}
<script>
	$(document).ready(function () {
		$('#div_id_product_option input:radio:not(:disabled):first').prop('checked', true);
	});
</script>
{% endblock %}