stagmenfashion/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = (
    [path("admin/", admin.site.urls), path("", include("web.urls", namespace="web"))]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

web/urls.py
from django.urls import path

from . import views


app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("category/<str:slug>/", views.CategoryProductListView.as_view(), name="category_list"),
    path("subcategory/<str:slug>/", views.SubcategoryProductListView.as_view(), name="subcategory_list"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("privacy-policy/", views.PrivacyPolicyView.as_view(), name="privacy_policy"),
    path("terms-and-conditions/", views.TermsAndConditionsView.as_view(), name="terms_and_conditions"),
    path("cookies-policy/", views.CookiesPolicyView.as_view(), name="cookies_policy"),
    path("refund-policy/", views.RefundPolicyView.as_view(), name="refund_policy"),
    path("product/<str:slug>/", views.ProductView.as_view(), name="product_view"),
    path("branch/<str:slug>/", views.BranchView.as_view(), name="branch_view"),
    path("checkout/<str:pk>/", views.CheckoutView.as_view(), name="checkout"),
    path("payment/<str:pk>/", views.PaymentView.as_view(), name="payment"),
    path("callback/verify/<str:pk>/", views.PaymentCallback.as_view(), name="payment_callback"),
    path("complete-order/<str:pk>/", views.CompleteOrderView.as_view(), name="complete_order"),
    path("track/", views.TrackOrdersView.as_view(), name="track_orders"),
    path("cart/", views.CartView.as_view(), name="cart"),
    path("order/delete/<str:pk>/", views.RemoveCartItemView.as_view(), name="order_delete"),
    path("orders/", views.OrderListView.as_view(), name="order_list"),
    path("orders/refresh/", views.refresh_orders, name="order_refresh"),
    path("order/<str:pk>/", views.OrderDetailView.as_view(), name="order_view"),
]

templates/web/partials/cart.html
{% load static thumbnail custom_filters humanize %}

<div class="w3-ch-sideBar w3-bar-block w3-card-2 w3-animate-right" style="display:none;right:0;" id="Cart">
    <div class="rightMenu-scroll">
        <div class="d-flex align-items-center justify-content-between slide-head py-3 px-3">
            <h4 class="cart_heading fs-md mb-0">Your Cart</h4>
            <button onclick="closeCart()" class="close_slide"><i class="ti-close"></i></button>
        </div>
        <div class="right-ch-sideBar">

            {% if cart_items %}
            <div class="cart_select_items pt-2">
                {% for item in cart_items %}
                <div class="d-flex align-items-center justify-content-between br-bottom px-3 py-3 item_parent">
                    <div class="cart_single d-flex align-items-center">
                        <div class="cart_selected_single_thumb">
                            <a href="#"><img src="{{item.product_option.product.image.medium.url}}" width="60" class="img-fluid" alt="" /></a>
                        </div>
                        <div class="cart_single_caption pl-2">
                            <h4 class="product_title fs-sm ft-medium mb-2 lh-1">{{item.product_option.product.name}}</h4>
                            <span class="d-block text-dark small">SIZE: {{item.product_option}}</span>
                            <p class="mb-0">
                                <span class="text-dark small mr-3">
                                    {{item.price|intcomma|get_currency:request.user}} 
                                </span>
                                <span class="text-dark small">
                                    QTY: {{item.quantity}}N
                                </span>
                            </p>
                            <h6 class="fs-sm mb-0 lh-1">{{item.subtotal|intcomma|get_currency:request.user}}</h6>
                        </div>
                    </div>
                    <div class="fls_last">
                        {% csrf_token %}
                        <button class="close_slide gray cartitem_rmvbutton" data-url="{% url 'web:order_delete' item.pk %}">
                            <i class="ti-close"></i>
                        </button>
                    </div>
                </div>
                {% endfor %}

            </div>
            
            <div class="d-flex align-items-center justify-content-between br-top br-bottom px-3 py-3">
                <h6 class="mb-0">Subtotal</h6>
                <h3 class="mb-0 ft-medium"><span id="totalValue">{{order.total|intcomma|get_currency:request.user}}</span></h3>
            </div>
            
            <div class="cart_action px-3 py-3">
                <div class="form-group">
                    <a href="{% url 'web:cart' %}" class="btn d-block full-width btn-dark">Shopping Cart</a>
                </div>
            </div>
            {% else %}

            <div class="d-flex align-items-center justify-content-between px-3 py-3">
                <h6 class="mb-0">Cart is Empty</h6>
            </div>
            {% endif %}
            
        </div>
    </div>
</div>

templates/web/partials/header.html
{% load static %}
<div class="top_banner">
	<p>FREE SHIPPING TO INDIA ON ALL ORDERS ABOVE ₹2999</p>
</div>

<div class="header header-light dark-text">
    <div class="container-fluid">
        <nav id="navigation" class="navigation navigation-landscape">
            <div class="nav-header">
                <button class="navbtn" onclick="openSidemenu()">
                    <svg height="25px" viewBox="-0.5 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M2 12.32H22" stroke="#000000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M2 18.32H22" stroke="#000000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M2 6.32001H22" stroke="#000000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </button>
                <a class="nav-brand" href="/">
                    <img src="{% static 'web/img/logo.png' %}" class="logo" alt="" />
                </a>
                <div class="mobile_nav">
                    <ul>
                        <li>
                            <a href="#" onclick="openSearch()">
                                <svg class="Icon Icon--search" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none"><path d="m18.031 16.617 4.283 4.282-1.415 1.415-4.282-4.283A8.96 8.96 0 0 1 11 20c-4.968 0-9-4.032-9-9s4.032-9 9-9 9 4.032 9 9a8.96 8.96 0 0 1-1.969 5.617Zm-2.006-.742A6.977 6.977 0 0 0 18 11c0-3.868-3.133-7-7-7-3.868 0-7 3.132-7 7 0 3.867 3.132 7 7 7a6.977 6.977 0 0 0 4.875-1.975l.15-.15Z" fill="#09121F"/></svg>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'web:track_orders' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="24" height="24" viewBox="0 0 368.666 368.666"><path d="M184.333 0C102.01 0 35.036 66.974 35.036 149.297c0 33.969 11.132 65.96 32.193 92.515 27.27 34.383 106.572 116.021 109.934 119.479l7.169 7.375 7.17-7.374c3.364-3.46 82.69-85.116 109.964-119.51 21.042-26.534 32.164-58.514 32.164-92.485C333.63 66.974 266.656 0 184.333 0zm101.462 229.355c-21.956 27.687-80.92 89.278-101.462 110.581-20.54-21.302-79.483-82.875-101.434-110.552-18.228-22.984-27.863-50.677-27.863-80.087C55.036 78.002 113.038 20 184.333 20c71.294 0 129.297 58.002 129.296 129.297 0 29.412-9.625 57.096-27.834 80.058z"/><path d="M184.333 59.265c-48.73 0-88.374 39.644-88.374 88.374s39.645 88.374 88.374 88.374 88.374-39.645 88.374-88.374-39.644-88.374-88.374-88.374zm0 156.748c-37.702 0-68.374-30.673-68.374-68.374 0-37.702 30.673-68.374 68.374-68.374s68.373 30.673 68.374 68.374c0 37.702-30.672 68.374-68.374 68.374z"/></svg>
                            </a>
                        </li>
                        <li>
                            <a href="#" onclick="openCart()">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none">
                                    <g clip-path="url(#a)"><path d="M20 22H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1Zm-1-2V4H5v16h14ZM9 6v2a3 3 0 1 0 6 0V6h2v2A5 5 0 1 1 7 8V6h2Z" fill="#09121F"/></g>
                                    <defs><clipPath id="a"><path fill="#fff" d="M0 0h24v24H0z"/></clipPath></defs>
                                </svg>
                                <span class="dn-counter theme-bg" id="totalItems">{{cart_items|length}}</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="nav-menus-wrapper" style="transition-property: none;">
             
                <ul class="nav-menu nav-menu-social align-to-right">
                    <li>
                        <a href="#" onclick="openSearch()">
                            <svg class="Icon Icon--search" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none"><path d="m18.031 16.617 4.283 4.282-1.415 1.415-4.282-4.283A8.96 8.96 0 0 1 11 20c-4.968 0-9-4.032-9-9s4.032-9 9-9 9 4.032 9 9a8.96 8.96 0 0 1-1.969 5.617Zm-2.006-.742A6.977 6.977 0 0 0 18 11c0-3.868-3.133-7-7-7-3.868 0-7 3.132-7 7 0 3.867 3.132 7 7 7a6.977 6.977 0 0 0 4.875-1.975l.15-.15Z" fill="#09121F"/></svg>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'web:track_orders' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="24" height="24" viewBox="0 0 368.666 368.666"><path d="M184.333 0C102.01 0 35.036 66.974 35.036 149.297c0 33.969 11.132 65.96 32.193 92.515 27.27 34.383 106.572 116.021 109.934 119.479l7.169 7.375 7.17-7.374c3.364-3.46 82.69-85.116 109.964-119.51 21.042-26.534 32.164-58.514 32.164-92.485C333.63 66.974 266.656 0 184.333 0zm101.462 229.355c-21.956 27.687-80.92 89.278-101.462 110.581-20.54-21.302-79.483-82.875-101.434-110.552-18.228-22.984-27.863-50.677-27.863-80.087C55.036 78.002 113.038 20 184.333 20c71.294 0 129.297 58.002 129.296 129.297 0 29.412-9.625 57.096-27.834 80.058z"/><path d="M184.333 59.265c-48.73 0-88.374 39.644-88.374 88.374s39.645 88.374 88.374 88.374 88.374-39.645 88.374-88.374-39.644-88.374-88.374-88.374zm0 156.748c-37.702 0-68.374-30.673-68.374-68.374 0-37.702 30.673-68.374 68.374-68.374s68.373 30.673 68.374 68.374c0 37.702-30.672 68.374-68.374 68.374z"/></svg>
                        </a>
                    </li>
                    <li>
                        <a href="#" onclick="openCart()">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none">
                                <g clip-path="url(#a)"><path d="M20 22H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1Zm-1-2V4H5v16h14ZM9 6v2a3 3 0 1 0 6 0V6h2v2A5 5 0 1 1 7 8V6h2Z" fill="#09121F"/></g>
                                <defs><clipPath id="a"><path fill="#fff" d="M0 0h24v24H0z"/></clipPath></defs>
                            </svg>
                            <span class="dn-counter theme-bg" id="totalItems">{{cart_items|length}}</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>
<div class="clearfix"></div>

templates/web/partials/menu.html
{% load static %}
<div class="w3-ch-sideBar left w3-bar-block w3-card-2 w3-animate-left" style="display:none;left:0;" id="Sidemenu">
    <div class="rightMenu-scroll">
        <div class="d-flex align-items-center justify-content-between slide-head py-3 px-3">
            <h4 class="cart_heading fs-md mb-0">Menu</h4>
            <button onclick="closeSidemenu()" class="close_slide"><i class="ti-close"></i></button>
        </div>

        <div class="p-4">

            <div class="single_filter_card mb-2">
                <h5><a href="/">Home</a></h5>
            </div>

            <div class="single_filter_card mb-2">
                <h5><a href="{% url 'web:product_list' %}">Products</a></h5>
            </div>

            <div class="single_filter_card mb-2">
                <h5><a href="{% url 'web:about' %}">About Us</a></h5>
            </div>

            <div class="single_filter_card mb-2">
                <h5><a href="{% url 'web:contact' %}">Contact</a></h5>
            </div>

            {% for category in categories %}
            <div class="single_filter_card mb-2">
                <h5>
                    <a href="{{category.get_absolute_url}}">{{category.name}}</a>
                    {% if category.get_subcategories %}
                    <a href="#{{category.slug}}" data-toggle="collapse" class="collapsed"
                        aria-expanded="false" role="button">
                        <i class="accordion-indicator ti-plus"></i>
                    </a>
                    {% endif %}
                </h5>
                {% if category.get_subcategories %}
                <div class="collapse" id="{{category.slug}}"
                    data-parent="#{{category.slug}}-categories">
                    <div class="card-body">
                        <div class="inner_widget_link">
                            <ul class="m-0 p-0">
                                {% for subcategory in category.get_subcategories %}
                                <li>
                                    <a href="{{subcategory.get_absolute_url}}">{{subcategory.name}}
                                        <span>{{subcategory.get_productcount}}</span>
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
            {% endfor %}

            <div class="single_filter_card mb-2">
                <h5><a href="{% url 'web:privacy_policy' %}">Privacy Policy</a></h5>
            </div>

            <div class="single_filter_card mb-2">
                <h5><a href="{% url 'web:terms_and_conditions' %}">Terms of Use</a></h5>
            </div>

            <div class="single_filter_card mb-2">
                <h5><a href="{% url 'web:cookies_policy' %}">Cookies Policy</a></h5>
            </div>

            <div class="single_filter_card mb-2">
                <h5><a href="{% url 'web:refund_policy' %}">Refund Policy</a></h5>
            </div>


        </div>
        
        <div class="p-4 mt-5">
            <ul class="list-inline">
                {% for s in socials %}
                <li class="list-inline-item p-0 border-0"><a href="{{s.link}}" target="_blank"><i class="lni {{s.media}}"></i></a></li>
                {% endfor %}
            </ul>
        </div>
        
    </div>
</div>

templates/web/partials/product_card.html
{% load static thumbnail custom_filters humanize %}

<div class="product_grid card">
    <div class="badge position-absolute ft-regular ab-left text-upper">{{product.badge|default:""}}</div>
    <div class="card-body">

        {% if product.status == "LaunchingSoon" %}
        <div class="ptag launching_soon">
            <div class="launching_soon_text">Launching Soon</div>
        </div>

        {% elif product.status == "OutofStock" %}
        <div class="ptag out_of_stock">
            <div class="out_of_stock_text">Out of Stock</div>
        </div>
        {% endif %}
     

        <div class="shop_thumb position-relative">
            <a class="card-img-top d-block overflow-hidden " href="{{product.get_absolute_url}}">
                <img class="card-img-top" src="{{product.image.medium.url}}" alt="...">
            </a>
        </div>

        {% if product.get_size_codes %}
        <div class="size_block">
            <div class="size-row">
                {% for size in product.get_size_codes %}
                <span class="size-item text-dark" data-id="{{size.pk}}"><strong>{{size}}</strong></span>
                {% endfor %}
            </div>
            <a class="text-center" href="{{product.image.url}}" data-lightbox="{{product.slug}}" data-title="{{product.name}}" class="size_add_to_cart">QUICK VIEW</a>
        </div>
        {% endif %}

    </div>

    <div class="card-footer b-0">
        <div class="text-left">
            <h5 class="fw-bolder fs-sm mb-0 lh-1 mb-1">
                <a href="{{product.get_absolute_url}}" class="text"><strong>{{product.name}}</strong></a>
            </h5>
            <h5 class="fw-bold fs-sm mb-0 lh-1 mb-1">
                {% if product.offer_price %}
                <a href="{{product.get_absolute_url}}" class="text mr-1"><del>{{product.sale_price|intcomma|get_currency:request.user}}</del></a>
                <a href="{{product.get_absolute_url}}" class="text text-danger">{{product.offer_price|intcomma|get_currency:request.user}}</a>
                {% else %}
                <a href="{{product.get_absolute_url}}" class="text text-danger">{{product.sale_price|intcomma|get_currency:request.user}}</a>
                {% endif %}
            </h5>
        </div>
    </div>
</div>

templates/web/partials/search.html
{% load static %}
<div class="w3-ch-sideBar w3-bar-block w3-card-2 w3-animate-right" style="display:none;right:0;" id="Search">
    <div class="rightMenu-scroll">
        <div class="d-flex align-items-center justify-content-between slide-head py-3 px-3">
            <h4 class="cart_heading fs-md mb-0">Search Products</h4>
            <button onclick="closeSearch()" class="close_slide"><i class="ti-close"></i></button>
        </div>

        <div class="cart_action px-3 py-4">
            <form class="form m-0 p-0" method="get" action="{% url 'web:product_list' %}">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Product Keyword.." name="query" value="{{request.GET.query}}" />
                </div>
                <div class="form-group mb-0">
                    <button type="button" class="btn d-block full-width btn-dark">Search Product</button>
                </div>
            </form>
        </div>

        <div class="d-flex align-items-center justify-content-center br-top br-bottom py-2 px-3">
            <h4 class="cart_heading fs-md mb-0">Hot Categories</h4>
        </div>

        <div class="cart_action px-3 py-3">
            <div class="row">
                {% for category in categories %}
                <div class="col-xl-4 col-lg-4 col-md-4 col-4 mb-3">
                    <div class="cats_side_wrap text-center">
                        <div class="sl_cat_01">
                            <div class="d-inline-flex align-items-center justify-content-center p-3 circle mb-2 gray">
                                <a href="{{category.get_absolute_url}}" class="d-block">
                                    <img src="{{category.icon.url}}" class="img-fluid" width="40" alt="" />
                                </a>
                            </div>
                        </div>
                        <div class="sl_cat_02">
                            <h6 class="m-0 ft-medium fs-sm"><a href="javascript:void(0);">{{category.name}}</a></h6>
                        </div>
                    </div>
                </div>
                {% endfor %}
                
                
            </div>
        </div>

    </div>
</div>

templates/web/partials/sizeguide.html
{% load static %}
<!-- Modal -->
<div class="modal fade" id="sizeModal" tabindex="-1" role="dialog" aria-labelledby="sizeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="sizeModalLabel">PRODUCT SIZE GUIDE</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"
                    style="width: 32px;height: 32px;">
                    <span aria-hidden="true"><i class="ti-close"></i></span>
                </button>
            </div>
            <div class="modal-body text-center">
                <h4>SIZE GUIDE </h4>
                <p>
                    All clothing is in UK sizing, designed to fit to the following body measurements. <br>
                    Please note garment measurments will vary depending on style.
                </p>
                
                <div class="d-flex flex-wrap justify-content-center">
                    
                    {% if product.subcategory.size_chart %}
                    <div class="column">
                        <div class="thumb">
                            <img src="{{product.subcategory.size_chart.url}}" alt="size guide" class="img-fluid" style="width:400px;max-width: 100%;">
                        </div>
                    </div>
                    {% endif %}

                    <div class="column w-100">
                        <div class="text-left">

                            <div class="table-container table-responsive mt-4">
                                <table class="table table-bordered text-dark mx-auto" style="width: auto;">
                                    <tr>
                                        <th>Size</th>
                                        <th>Waist</th>
                                        <th>Rise</th>
                                        <th>Thighs</th>
                                        <th>Inseam Length</th>
                                        <th>Outseam Length</th>
                                        <th>Bottom Hem</th>
                                    </tr>
                                    {% for size in object.get_sizes %}
                                    <tr>
                                        <td>{{size.size.name}}</td>
                                        <td>{{size.waist|default:"-"}}</td>
                                        <td>{{size.rise|default:"-"}}</td>
                                        <td>{{size.thighs|default:"-"}}</td>
                                        <td>{{size.inseem_length|default:"-"}}</td>
                                        <td>{{size.length|default:"-"}}</td>
                                        <td>{{size.bottom_size|default:"-"}}</td>
                                    </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>